'use client';

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import styles from './page.module.css';
import { getSavedListings, deleteListing, generateEtsyListing, type SavedListing, type EtsyListing } from './etsyGenerator';
import { exportToExcel } from './excelExport';

export default function MyListingsPage() {
    const [listings, setListings] = useState<SavedListing[]>([]);
    const [exportModal, setExportModal] = useState<{ listing: SavedListing; etsy: EtsyListing } | null>(null);
    const [copied, setCopied] = useState<'title' | 'tags' | 'desc' | 'all' | null>(null);
    const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);

    const reload = useCallback(() => setListings(getSavedListings()), []);

    useEffect(() => { reload(); }, [reload]);

    const openExport = (listing: SavedListing) => {
        const etsy = generateEtsyListing(listing);
        setExportModal({ listing, etsy });
    };

    const copyText = async (text: string, key: typeof copied) => {
        await navigator.clipboard.writeText(text);
        setCopied(key);
        setTimeout(() => setCopied(null), 2000);
    };

    const downloadListing = (etsy: EtsyListing, title: string) => {
        const content = `ETSY LISTING — ${title}
Generated by Riolls Jewels AI Studio
═══════════════════════════════════════

TITLE (copy exactly):
${etsy.title}

─────────────────────────────────────
CATEGORY: ${etsy.category}
SUGGESTED PRICE: ${etsy.suggested_price_usd}

─────────────────────────────────────
13 TAGS (paste one per tag field):
${etsy.tags.map((t, i) => `${i + 1}. ${t}`).join('\n')}

─────────────────────────────────────
DESCRIPTION (paste into Etsy description field):

${etsy.description}

─────────────────────────────────────
AI DISCLOSURE (required by Etsy policy):
${etsy.ai_disclosure}
`;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `etsy-listing-${title.replace(/\s+/g, '-').slice(0, 40)}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleDelete = (id: string) => {
        if (deleteConfirm === id) {
            deleteListing(id);
            reload();
            setDeleteConfirm(null);
        } else {
            setDeleteConfirm(id);
            setTimeout(() => setDeleteConfirm(null), 3000);
        }
    };

    return (
        <div className={styles.page}>
            {/* Header */}
            <div className={styles.header}>
                <div className={styles.headerInner}>
                    <div>
                        <span className={styles.eyebrow}>AI Studio</span>
                        <h1 className={styles.heading}>My Design Listings</h1>
                        <p className={styles.sub}>Save designs from the AI Studio and export ready-to-publish Etsy listings.</p>
                    </div>
                    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                        <Link href="/etsy-excel-generator" className={styles.newBtn} style={{ background: 'rgba(201, 169, 110, 0.1)', border: '1px solid currentColor', color: '#c9a96e' }}>
                            Upload Photos → Etsy Excel
                        </Link>
                        <Link href="/ai-studio/step-1" className={styles.newBtn}>
                            + Create New Design
                        </Link>
                    </div>
                </div>
            </div>

            {/* Content */}
            <div className={styles.content}>
                {listings.length === 0 ? (
                    <div className={styles.empty}>
                        <div className={styles.emptyIcon}>
                            <svg width="56" height="68" viewBox="0 0 80 96" fill="rgba(201,169,110,0.12)" stroke="#C9A96E" strokeWidth="1">
                                <polygon points="40,4 76,24 62,92 18,92 4,24" />
                                <polygon points="40,4 62,24 40,36 18,24" />
                                <line x1="18" y1="24" x2="62" y2="24" />
                            </svg>
                        </div>
                        <h2 className={styles.emptyTitle}>No listings saved yet</h2>
                        <p className={styles.emptySub}>Generate designs in the AI Studio, then click <strong>"Save to My Listings"</strong> to store them here and export Etsy listings.</p>
                        <Link href="/ai-studio/step-1" className={styles.emptyBtn}>
                            Go to AI Studio →
                        </Link>
                    </div>
                ) : (
                    <>
                        <div className={styles.statsBar}>
                            <span className={styles.statsCount}>{listings.length} design{listings.length !== 1 ? 's' : ''} saved</span>
                            <span className={styles.statsHint}>Click "Export Etsy Listing" on any design to get a ready-to-publish listing file</span>
                            <button
                                className={styles.excelBtn}
                                onClick={() => exportToExcel(listings)}
                                title="Download all listings as Excel file"
                            >
                                ⬇ Export All to Excel
                            </button>
                        </div>
                        <div className={styles.grid}>
                            {listings.map(listing => (
                                <div key={listing.id} className={styles.card}>
                                    {/* Image */}
                                    <div className={styles.cardImg}>
                                        {listing.concept.image_data ? (
                                            <img
                                                src={listing.concept.image_data}
                                                alt={listing.concept.title}
                                                className={styles.cardImgEl}
                                            />
                                        ) : (
                                            <div className={styles.cardImgPlaceholder}>
                                                <svg width="40" height="48" viewBox="0 0 80 96" fill="rgba(201,169,110,0.1)" stroke="#C9A96E" strokeWidth="1.5">
                                                    <polygon points="40,4 76,24 62,92 18,92 4,24" />
                                                    <polygon points="40,4 62,24 40,36 18,24" />
                                                    <line x1="18" y1="24" x2="62" y2="24" />
                                                </svg>
                                            </div>
                                        )}
                                        <div className={styles.cardBadge}>
                                            {typeof listing.profile.pieceType === 'string'
                                                ? listing.profile.pieceType
                                                : listing.profile.pieceType?.[0] ?? 'Design'}
                                        </div>
                                    </div>

                                    {/* Info */}
                                    <div className={styles.cardBody}>
                                        <h3 className={styles.cardTitle}>{listing.concept.title}</h3>
                                        <p className={styles.cardDesc}>{listing.concept.description}</p>
                                        <p className={styles.cardDate}>
                                            Saved {new Date(listing.savedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                                        </p>
                                        <div className={styles.cardDetail}>
                                            {listing.concept.hero_material && (
                                                <span className={styles.cardTag}>{listing.concept.hero_material}</span>
                                            )}
                                            {(Array.isArray(listing.profile.metalColor) ? listing.profile.metalColor[0] : listing.profile.metalColor) && (
                                                <span className={styles.cardTag}>{Array.isArray(listing.profile.metalColor) ? listing.profile.metalColor[0] : listing.profile.metalColor}</span>
                                            )}
                                        </div>
                                    </div>

                                    {/* Actions */}
                                    <div className={styles.cardActions}>
                                        <button
                                            className={styles.exportBtn}
                                            onClick={() => openExport(listing)}
                                        >
                                            Export Etsy Listing
                                        </button>
                                        <button
                                            className={`${styles.deleteBtn} ${deleteConfirm === listing.id ? styles.deleteBtnConfirm : ''}`}
                                            onClick={() => handleDelete(listing.id)}
                                        >
                                            {deleteConfirm === listing.id ? 'Tap again to confirm' : '✕'}
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </>
                )}
            </div>

            {/* Export Modal */}
            {exportModal && (
                <div className={styles.modalOverlay} onClick={() => setExportModal(null)}>
                    <div className={styles.modal} onClick={e => e.stopPropagation()}>
                        <div className={styles.modalHeader}>
                            <div>
                                <span className={styles.eyebrow}>Etsy Listing Export</span>
                                <h2 className={styles.modalTitle}>{exportModal.listing.concept.title}</h2>
                            </div>
                            <button className={styles.modalClose} onClick={() => setExportModal(null)}>✕</button>
                        </div>

                        <div className={styles.modalBody}>
                            {/* Meta row */}
                            <div className={styles.metaRow}>
                                <div className={styles.metaItem}>
                                    <span className={styles.metaLabel}>Category</span>
                                    <span className={styles.metaValue}>{exportModal.etsy.category}</span>
                                </div>
                                <div className={styles.metaItem}>
                                    <span className={styles.metaLabel}>Suggested Price</span>
                                    <span className={styles.metaValueGold}>{exportModal.etsy.suggested_price_usd}</span>
                                </div>
                            </div>

                            {/* Title */}
                            <div className={styles.section}>
                                <div className={styles.sectionHeader}>
                                    <span className={styles.sectionLabel}>ETSY TITLE</span>
                                    <button className={styles.copyBtn} onClick={() => copyText(exportModal.etsy.title, 'title')}>
                                        {copied === 'title' ? '✓ Copied!' : 'Copy'}
                                    </button>
                                </div>
                                <div className={styles.sectionBox}>
                                    <p className={styles.sectionText}>{exportModal.etsy.title}</p>
                                    <span className={styles.charCount}>{exportModal.etsy.title.length}/140 chars</span>
                                </div>
                            </div>

                            {/* Tags */}
                            <div className={styles.section}>
                                <div className={styles.sectionHeader}>
                                    <span className={styles.sectionLabel}>13 TAGS</span>
                                    <button className={styles.copyBtn} onClick={() => copyText(exportModal.etsy.tags.join(', '), 'tags')}>
                                        {copied === 'tags' ? '✓ Copied!' : 'Copy All'}
                                    </button>
                                </div>
                                <div className={styles.tagsGrid}>
                                    {exportModal.etsy.tags.map((tag, i) => (
                                        <span key={i} className={styles.tagPill}>
                                            <span className={styles.tagNum}>{i + 1}</span>
                                            {tag}
                                        </span>
                                    ))}
                                </div>
                            </div>

                            {/* Description */}
                            <div className={styles.section}>
                                <div className={styles.sectionHeader}>
                                    <span className={styles.sectionLabel}>DESCRIPTION</span>
                                    <button className={styles.copyBtn} onClick={() => copyText(exportModal.etsy.description, 'desc')}>
                                        {copied === 'desc' ? '✓ Copied!' : 'Copy'}
                                    </button>
                                </div>
                                <textarea
                                    className={styles.descArea}
                                    value={exportModal.etsy.description}
                                    readOnly
                                    rows={12}
                                />
                            </div>
                        </div>

                        {/* Modal Footer */}
                        <div className={styles.modalFooter}>
                            <button
                                className={styles.copyAllBtn}
                                onClick={() => copyText(
                                    `TITLE:\n${exportModal.etsy.title}\n\nTAGS:\n${exportModal.etsy.tags.join(', ')}\n\nDESCRIPTION:\n${exportModal.etsy.description}`,
                                    'all'
                                )}
                            >
                                {copied === 'all' ? '✓ All Copied!' : 'Copy Everything'}
                            </button>
                            <button
                                className={styles.downloadBtn}
                                onClick={() => downloadListing(exportModal.etsy, exportModal.listing.concept.title)}
                            >
                                Download .txt File
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
